import { mkdirSync, writeFileSync } from 'node:fs'
import { apiSpecCategories, commonStructNames } from '@saltify/milky-types/namings'
import { camelCase } from 'change-case'

mkdirSync('./src/gen', { recursive: true })

const typeExport = new Set(commonStructNames)
const protoStructImport = new Set()

const protoStructFields = []
const rawEndpointsDeclarations = []
const clientEndpointsDeclarations = []
for (const category of apiSpecCategories) {
  clientEndpointsDeclarations.push(`  ${camelCase(category.key)}: {`)
  for (const spec of category.apiSpecs) {
    if (spec.inputStructName) {
      typeExport.add(spec.inputStructName)
      protoStructImport.add(spec.inputStructName)
    }
    if (spec.outputStructName) {
      typeExport.add(spec.outputStructName)
      protoStructImport.add(spec.outputStructName)
    }

    protoStructFields.push(`  '${spec.endpoint}': [${spec.inputStructName ?? 'null'}, ${spec.outputStructName ?? 'null'}],`)

    rawEndpointsDeclarations.push(`  ${spec.endpoint}: (${spec.inputStructName ? `param: ${spec.inputStructName}` : 'params?: undefined | null'}) => ${spec.outputStructName ?? 'void'};`)
    clientEndpointsDeclarations.push(`    ${camelCase(spec.endpoint)}: '${spec.endpoint}',`)
  }
  clientEndpointsDeclarations.push(`  },`)
}

const typeNames = [...typeExport]
const chunks = []
chunks.push(`/* eslint-disable eslint-comments/no-unlimited-disable */
/* eslint-disable */
// This file is generated by scripts/generate-api.ts`)

chunks.push(`import type { ${typeNames.join(', ')} } from '@saltify/milky-types'`)

chunks.push(`export type MilkyRawEndpoints = {`)
chunks.push(...rawEndpointsDeclarations)
chunks.push(`}`)
chunks.push('')
chunks.push(`export const clientEndpointNames = {`)
chunks.push(...clientEndpointsDeclarations)
chunks.push(`} as const`)
chunks.push(`export type MilkyClientEndpointNames = typeof clientEndpointNames`)

chunks.push(`export type { ${typeNames.join(', ')} }`)

writeFileSync('./src/gen/types.ts', chunks.join('\n'))

chunks.length = 0

chunks.push(`/* eslint-disable eslint-comments/no-unlimited-disable */
/* eslint-disable */
// This file is generated by scripts/generate-api.ts`)

chunks.push(`import { ${[...protoStructImport].join(', ')} } from '@saltify/milky-types'`)

chunks.push(`type MilkyProtoStruct = { safeParseAsync: (value: unknown) => Promise<any> } | null`)
chunks.push(`export const milkyProto: Record<string, [MilkyProtoStruct, MilkyProtoStruct]> = {`)
chunks.push(...protoStructFields)
chunks.push(`}`)

chunks.push(`export { ${commonStructNames.join(', ')} } from '@saltify/milky-types'`)

writeFileSync('./src/gen/proto.ts', chunks.join('\n'))
