import { mkdirSync, writeFileSync } from 'node:fs'
import { apiSpecCategories, commonStructNames } from '@saltify/milky-types/namings'
import { camelCase } from 'change-case'

mkdirSync('./src/gen', { recursive: true })

const typeExport = new Set(commonStructNames)
const zodStructImport = new Set()

const zodStructsFields = []
const rawEndpointsDeclarations = []
const clientEndpointsDeclarations = []
for (const category of apiSpecCategories) {
  clientEndpointsDeclarations.push(`  ${camelCase(category.key)}: {`)
  for (const spec of category.apiSpecs) {
    if (spec.inputStructName) {
      typeExport.add(spec.inputStructName)
      zodStructImport.add(spec.inputStructName)
      spec.outputStructName && zodStructImport.add(spec.outputStructName)
      zodStructsFields.push(`  '${spec.endpoint}': [${spec.inputStructName ? `z.object(${spec.inputStructName})` : 'z.void()'}, ${spec.outputStructName ? `z.object(${spec.outputStructName})` : 'z.void()'}],`)
    }
    if (spec.outputStructName) {
      typeExport.add(spec.outputStructName)
    }

    rawEndpointsDeclarations.push(`  ${spec.endpoint}: (${spec.inputStructName ? `param: ${spec.inputStructName}` : 'params?: undefined | null'}) => ${spec.outputStructName ?? 'void'};`)
    clientEndpointsDeclarations.push(`    ${camelCase(spec.endpoint)}: '${spec.endpoint}',`)
  }
  clientEndpointsDeclarations.push(`  },`)
}

const typeNames = [...typeExport]
const chunks = []
chunks.push(`/* eslint-disable eslint-comments/no-unlimited-disable */
/* eslint-disable */
// This file is generated by scripts/generate-api.ts`)

chunks.push(`import type { ${typeNames.join(', ')} } from '@saltify/milky-types'`)

chunks.push(`export type MilkyRawEndpoints = {`)
chunks.push(...rawEndpointsDeclarations)
chunks.push(`}`)
chunks.push('')
chunks.push(`export const clientEndpointNames = {`)
chunks.push(...clientEndpointsDeclarations)
chunks.push(`} as const`)
chunks.push(`export type MilkyClientEndpointNames = typeof clientEndpointNames`)

chunks.push(`export type { ${typeNames.join(', ')} }`)

writeFileSync('./src/gen/types.ts', chunks.join('\n'))

chunks.length = 0

chunks.push(`/* eslint-disable eslint-comments/no-unlimited-disable */
/* eslint-disable */
// This file is generated by scripts/generate-api.ts`)

chunks.push(`import { z } from 'zod'`)
chunks.push(`import { ${[...zodStructImport].join(', ')} } from '@saltify/milky-types'`)

chunks.push(`export const milkyProto: Record<string, [z.ZodTypeAny, z.ZodTypeAny]> = {`)
chunks.push(...zodStructsFields)
chunks.push(`}`)

writeFileSync('./src/gen/proto.ts', chunks.join('\n'))
